### ISSUE TITLE
Dragged Down speech.

### ISSUE THREAD

**Issue by Unusualiscool** [ChuckTheSheep/zomboid-cnd-speech#10]
I know this may make no sense, but here's my ideas for the small amount of words your character can get out before D E A T H:

"OH SHIT! OH SHIT! SHIT SHIT SHI-!"
"NO OH GOD HELP AHHHHHH!"
"OH GOD! OH GOD! AHHHHH!"
and a rare chance of
"Man I'm hungry."
(As a joke of course :P)

**Comment by yooksi** [comment]
@Unusualiscool Thanks for the suggestion, feel free to join `#pz-cnd-speech` in [Coco Labs](https://discord.gg/vCeydWCbd9) to talk about the mod.
