### ISSUE TITLE
About Translation

### ISSUE THREAD

**Issue by Batur123** [ChuckTheSheep/zomboid-cnd-speech#32]
Does translation has to be exact same words in _EN file? Is localization allowed? (Like adding different words but same meaning)

**Comment by ChuckTheSheep** [comment]
The translation does not have to be exact - in fact, you can have a different amount of lines per language. As long as the general theme matches.

**Comment by Batur123** [comment]
It is matches but problem is Turkish language is not sharing same rules in English. So we have subject in the beginning and verb in the end. What happens if i dont use --UI_Phrases_SWEARskipwords ? 

Other translates and phrases are finished its quite good. But SWEARskipwords breaks the Turkish language a lot.

**Comment by ChuckTheSheep** [comment]
Swear skip words breaks English too sadly, haha. I may be removing it soon for this reason.

**Comment by ChuckTheSheep** [comment]
I have removed SWEARSkipWords and Fucks from the phraseSets.
