### ISSUE TITLE
Bug: Boredom resetting at 25% when invoking Conditional Speech

### ISSUE THREAD

**Issue by Mr-Beard** [ChuckTheSheep/zomboid-cnd-speech#39]
Every time Boredom gets to 25% and invokes a conditional speech, it flashes the speech line and moddle on the screen for a brief moment then immediately drops Boredom back down to about 20%, and this happens every time it hits 25% Boredom (so it will never progress to higher tiers of boredom).

I've troubleshot by loading only this mod (and Easy Config Chucked since it's required), loading up a brand new game (with every difficulty and/or sandbox imaginable). I've also resubbed and validated files and it only happens with this mod and with the Boredom moodle.

**Comment by ChuckTheSheep** [comment]
The mod operates in reaction to moodles. It's not a widely known thing but talking in game relieves boredom. I imagine what is happening is the player is reacting to becoming more bored - relieving some boredom - then it creeps back up to repeat.
