### ISSUE TITLE
Speech no longer displaying for anyone

### ISSUE THREAD

**Issue by tbc56** [ChuckTheSheep/zomboid-cnd-speech#48]
after recent update any normal chat in /say is no longer displaying for anyone other than the speaker. Chat isnt recorded in the log and it seems to be treated as speech done from the mod

**Comment by ChuckTheSheep** [comment]
So no one can see other people's chat?

**Comment by tbc56** [comment]
Correct. If i turn on the settings that make it so conditional speech doesnt attract zombies then local chat wont even display above your characters head as well.

**Comment by ChuckTheSheep** [comment]
https://imgur.com/uXWVDu6

**Comment by ChuckTheSheep** [comment]
Ah, that might be the issue. I'll check that out.

**Comment by ChuckTheSheep** [comment]
Should be fixed with a823389b0fbb5a4df6b68ef4e37bc6acc9516fa8.
